- core/modules/facture/doc/pdf_crabe_btp.modules.php
- langs/fr_FR/btp.lang
Ajout récap des situations précédentes au tableau_tot
Corrections visuelles
Recalcul des sous-totaux de situations précédentes
> Modèle pdf

- core/modules/facture/doc/pdf_crabe_btp.modules.php
- langs/fr_FR/btp.lang
Reverts ATM-Consulting/module_dolibarr_btp#5
> Revert "Maybe last modif détail situation précédente"

- core/modules/facture/doc/pdf_sponge_btp.modules.php
Rend la lecture du total des situations sur le PDF plus facile. (R&D BTP)
> Change previous situation total display

- core/modules/facture/doc/pdf_sponge_btp.modules.php
- langs/fr_FR/btp.lang
Spécial branch 8.0_btp + fix des montants
> Allow display retained warranty

- core/modules/facture/doc/pdf_sponge_btp.modules.php
https://github.com/ATM-Consulting/dolibarr/pull/90
https://github.com/ATM-Consulting/dolibarr_module_pdfevolution/pull/8
Mise en place des retenues de garanties pour toutes les factures.
TK10462
> NEW retained warranty available for all invoices

- core/modules/facture/doc/pdf_sponge_btp.modules.php
- Fix : pdf col size and line break
> FIX : pdf col size and line break

- ChangeLog.md
- admin/setup_btp.php
- core/modules/modBtp.class.php
> Fix V13 Compatibility

- ChangeLog.md
- core/modules/modBtp.class.php
Le module est déjà compatible v14 ; les seuls changements concernent le descripteur et le ChangeLog.
> FIX v14 compat: no change required; module descriptor updated

- ChangeLog.md
- core/modules/modBtp.class.php
cf. https://github.com/ATM-Consulting/module_dolibarr_btp/pull/32
> PULLUP FIX v14 compat: no change required; module descriptor updated

- ChangeLog.md
- core/modules/facture/doc/pdf_sponge_btp.modules.php
- core/modules/modBtp.class.php
- langs/fr_FR/btp.lang
Changement de traductions sur une facture de situation.
> Fix traduction sur une facture de situation

- ChangeLog.md
- core/modules/facture/doc/pdf_sponge_btp.modules.php
- core/modules/modBtp.class.php
- langs/fr_FR/btp.lang
Changements de traductions sur une facture de situation.
> PULLUP : Fix des trads sur la facture de situation

- ChangeLog.md
- core/modules/facture/doc/pdf_sponge_btp.modules.php
- core/modules/modBtp.class.php
https://github.com/ATM-Consulting/module_dolibarr_btp/pull/37
> PULLUP : fix display ttc pdf

- ChangeLog.md
- admin/setup_btp.php
- class/actions_btp.class.php
- core/modules/modBtp.class.php
- langs/en_US/btp.lang
- langs/fr_FR/btp.lang
- lib/btp.lib.php
NEW : Intégration bénéfice prévisionnel sur vue d'ensemble chantier
> New project show forecast profit

- ChangeLog.md
- core/modules/facture/doc/pdf_sponge_btp.modules.php
- core/modules/modBtp.class.php
FIX : taille du tableau préliminaire variable
> fix tableau btp

- ChangeLog.md
- core/modules/facture/doc/pdf_sponge_btp.modules.php
- core/modules/modBtp.class.php
FIX : taille du tableau préliminaire variable
> PULL UP Fix 1.3 tableau btp

- ChangeLog.md
- core/modules/modBtp.class.php
FIX : Compatibilité v16 : fix doublon this family
> FIX : Compatibilité v16 : fix doublon this family

- ChangeLog.md
- core/modules/facture/doc/pdf_sponge_btp.modules.php
- core/modules/modBtp.class.php
#FIX : fatal error dans le modèle sponge_btp dû à une fuite de mémoire - *04/08/2022* - 1.3.2
- suppression de caches inutiles
- optimisation des calculs en boucle
> Fix 1.3 fatal error memory leak

- ChangeLog.md
- core/modules/facture/doc/pdf_sponge_btp.modules.php
- core/modules/modBtp.class.php
#FIX : fatal error dans le modèle sponge_btp dû à une fuite de mémoire - *04/08/2022* - 1.3.2
- suppression de caches inutiles
- optimisation des calculs en boucle
> PULL UP : Fix 1.3 fatal error memory leak

- ChangeLog.md
- core/modules/facture/doc/pdf_crabe_btp.modules.php
- core/modules/modBtp.class.php
FIX : modification du bas de page récapitulatif des situations
> FIX : modification du bas de page récapitulatif des situations

- ChangeLog.md
- core/modules/facture/doc/pdf_sponge_btp.modules.php
- core/modules/modBtp.class.php
FIX : warning foreach in sponge
> fix foreach

- ChangeLog.md
- core/modules/facture/doc/pdf_sponge_btp.modules.php
- core/modules/modBtp.class.php
FIX : warning foreach in sponge
> PULL UP main : Fix 1.3 invalid foreach

- ChangeLog.md
- core/modules/facture/doc/pdf_crabe_btp.modules.php
- core/modules/facture/doc/pdf_sponge_btp.modules.php
- core/modules/modBtp.class.php
FIX : setNewPage bad type hint
> fix type hint

- ChangeLog.md
- core/modules/facture/doc/pdf_crabe_btp.modules.php
- core/modules/facture/doc/pdf_sponge_btp.modules.php
- core/modules/modBtp.class.php
FIX : setNewPage bad type hint
> PULL UP main : Fix set new page type hint

- ChangeLog.md
- core/modules/facture/doc/pdf_sponge_btp.modules.php
- core/modules/modBtp.class.php
Warnings lors de la génération du pdf Sponge
> FIX - Warnings lors de la génération du pdf Sponge

- ChangeLog.md
- core/modules/facture/doc/pdf_sponge_btp.modules.php
- core/modules/modBtp.class.php
PULL UP de cette PR : 
https://github.com/ATM-Consulting/module_dolibarr_btp/pull/66
> PULLUP - FIX - Warnings lors de la génération du pdf Sponge

- ChangeLog.md
- core/modules/modBtp.class.php
> FIX : No depends on modules

- ChangeLog.md
- core/modules/modBtp.class.php
> PULLUP [main] | FIX : No depends on modules
